name: Move closed card to Review
on:
  issues:
    types:
      - closed
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
        with:
          project: WhatsappBot Pure
          column: 👀 In review
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}